import { Assessment, Finding, Repository, ActivityEvent } from "../types";

export const mockAssessments: Assessment[] = [
  {
    id: "ass-1",
    projectName: "Nexus AI Copilot",
    repoUrl: "https://github.com/nexus/copilot",
    branch: "main",
    status: "Completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    score: 62,
    riskLevel: "High"
  },
  {
    id: "ass-2",
    projectName: "RAG Search Engine v2",
    repoUrl: "https://gitlab.com/acme/rag-search",
    branch: "develop",
    status: "Completed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    score: 85,
    riskLevel: "Medium"
  },
  {
    id: "ass-3",
    projectName: "Internal Legal Assistant",
    repoUrl: "https://github.com/legal/assistant",
    branch: "main",
    status: "Running",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    score: 0,
    riskLevel: "Info"
  },
  {
    id: "ass-4",
    projectName: "Customer Support Bot",
    repoUrl: "https://github.com/support/bot",
    branch: "staging",
    status: "Failed",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    score: 0,
    riskLevel: "Info"
  },
  {
    id: "ass-5",
    projectName: "Financial Data Extractor",
    repoUrl: "https://bitbucket.org/finance/extractor",
    branch: "main",
    status: "Draft",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    score: 0,
    riskLevel: "Info"
  }
];

export const mockFindings: Finding[] = [
  {
    id: "fnd-1",
    assessmentId: "ass-1",
    title: "Untrusted retrieved content inserted into system prompt without sanitization",
    category: "RAG",
    severity: "Critical",
    confidence: "High",
    description: "The application inserts content retrieved from the vector store directly into the system prompt. If the vector store contains poisoned documents, this could lead to a prompt injection attack overriding system instructions.",
    affectedFile: "rag_pipeline.py",
    recommendation: "Sanitize retrieved content or use a rigid templating structure that separates instructions from data. Consider using the ChatML format with clear role separation.",
    status: "Open"
  },
  {
    id: "fnd-2",
    assessmentId: "ass-1",
    title: "System prompt is returned in debug API response",
    category: "Data Leakage",
    severity: "Critical",
    confidence: "High",
    description: "The /api/v1/chat/debug endpoint returns the full conversation history including the initial system prompt. This exposes sensitive instructions and potential hidden tools.",
    affectedFile: "/api/v1/chat/debug",
    recommendation: "Remove the system prompt from debug responses or restrict the debug endpoint to authenticated administrators only.",
    status: "Open"
  },
  {
    id: "fnd-3",
    assessmentId: "ass-1",
    title: "Agent action route lacks confirmation gate for external email send",
    category: "Tool Abuse",
    severity: "High",
    confidence: "High",
    description: "The AI agent has access to an email sending tool but there is no human-in-the-loop confirmation step before emails are dispatched.",
    affectedFile: "agents/email_handler.py",
    recommendation: "Implement a confirmation gate that requires a user to explicitly approve any outbound communications initiated by the agent.",
    status: "Acknowledged"
  },
  {
    id: "fnd-4",
    assessmentId: "ass-1",
    title: "Prompt and response logging may expose PII and sensitive data",
    category: "Logging",
    severity: "High",
    confidence: "Medium",
    description: "Raw prompts and completions are being logged to standard output without any redaction, potentially violating data privacy policies.",
    affectedFile: "middleware/logging.py",
    recommendation: "Implement a PII redaction layer before logging, or disable full prompt logging in production environments.",
    status: "Open"
  },
  {
    id: "fnd-5",
    assessmentId: "ass-1",
    title: "No rate limiting on AI inference endpoint",
    category: "Rate Limiting",
    severity: "High",
    confidence: "High",
    description: "The primary inference endpoint allows unlimited requests, making the application vulnerable to cost exhaustion (Denial of Wallet) attacks.",
    affectedFile: "/api/v1/chat/completions",
    recommendation: "Implement token-bucket rate limiting per user/tenant.",
    status: "Resolved"
  },
  {
    id: "fnd-6",
    assessmentId: "ass-1",
    title: "User input passed to tool call without schema validation",
    category: "Tool Abuse",
    severity: "Medium",
    confidence: "Medium",
    description: "Arguments generated by the LLM for the calendar tool are not validated against a JSON schema before execution.",
    affectedFile: "tools/calendar.py",
    recommendation: "Use a validation library (e.g., Pydantic) to strictly validate all LLM-generated arguments before executing tool functions.",
    status: "Open"
  },
  {
    id: "fnd-7",
    assessmentId: "ass-1",
    title: "Missing tenant isolation in RAG retrieval",
    category: "Auth",
    severity: "Medium",
    confidence: "High",
    description: "Vector database queries do not include a tenant ID filter, potentially allowing one customer to retrieve chunks from another customer's documents.",
    affectedFile: "retrieval/search.py",
    recommendation: "Always include the current tenant ID in the metadata filter of vector search queries.",
    status: "Open"
  },
  {
    id: "fnd-8",
    assessmentId: "ass-1",
    title: "LLM output rendered as HTML without escaping",
    category: "Data Leakage",
    severity: "Medium",
    confidence: "Medium",
    description: "The frontend renders the LLM's Markdown output directly to HTML without proper sanitization, opening a potential XSS vector if the LLM is convinced to output malicious scripts.",
    affectedFile: "frontend/ChatMessage.tsx",
    recommendation: "Use a secure Markdown renderer with a strict HTML sanitizer (like DOMPurify).",
    status: "Acknowledged"
  },
  {
    id: "fnd-9",
    assessmentId: "ass-1",
    title: "API key stored in environment variable accessible to LLM context",
    category: "Data Leakage",
    severity: "Low",
    confidence: "Low",
    description: "Configuration is loaded fully into memory and might be accessible if the LLM gains code execution capabilities.",
    affectedFile: "config/settings.py",
    recommendation: "Scope environment variables tightly and do not pass full config objects into contexts where they aren't fully needed.",
    status: "Open"
  },
  {
    id: "fnd-10",
    assessmentId: "ass-1",
    title: "No spend cap configured on AI provider account",
    category: "Rate Limiting",
    severity: "Low",
    confidence: "Low",
    description: "The underlying OpenAI/Anthropic account does not have a hard spending limit set.",
    affectedFile: "Infrastructure",
    recommendation: "Configure hard spend limits in the provider's billing dashboard.",
    status: "Open"
  }
];

export const mockRepositories: Repository[] = [
  { id: "repo-1", provider: "github", name: "nexus/copilot", url: "https://github.com/nexus/copilot", defaultBranch: "main", lastScanned: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), assessmentCount: 3, status: "Active" },
  { id: "repo-2", provider: "gitlab", name: "acme/rag-search", url: "https://gitlab.com/acme/rag-search", defaultBranch: "develop", lastScanned: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), assessmentCount: 1, status: "Active" },
  { id: "repo-3", provider: "github", name: "legal/assistant", url: "https://github.com/legal/assistant", defaultBranch: "main", lastScanned: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), assessmentCount: 4, status: "Active" },
  { id: "repo-4", provider: "bitbucket", name: "finance/extractor", url: "https://bitbucket.org/finance/extractor", defaultBranch: "main", lastScanned: null, assessmentCount: 0, status: "Never Scanned" },
  { id: "repo-5", provider: "github", name: "support/bot", url: "https://github.com/support/bot", defaultBranch: "staging", lastScanned: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(), assessmentCount: 2, status: "Error" },
];

export const mockActivity: ActivityEvent[] = [
  { id: "act-1", type: "assessment_completed", title: "Assessment completed for Nexus AI Copilot", timestamp: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
  { id: "act-2", type: "finding_detected", title: "Critical finding detected in RAG Search Engine v2", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
  { id: "act-3", type: "repo_connected", title: "Connected repository legal/assistant", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
  { id: "act-4", type: "report_exported", title: "Report exported for Customer Support Bot", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
  { id: "act-5", type: "finding_detected", title: "High severity finding detected in Nexus AI Copilot", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString() },
  { id: "act-6", type: "assessment_completed", title: "Assessment completed for Financial Data Extractor", timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString() },
];
